# Generated by Django 3.2.6 on 2021-08-31 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_rename_snacks_snack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='title',
            new_name='name',
        ),
    ]
